package cn.zzrfdsn.bos1.model;
// Generated 2019-8-18 14:23:26 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private String name;
	private String code;
	private String description;
	private Set<Permit> permits = new HashSet<Permit>(0);
	private Set<User> users = new HashSet<User>(0);

	public String getOwnPermits() {
		if (permits == null||permits.size()<1) {
			return "";
		}
		StringBuffer sb = new StringBuffer();
		for (Permit permit : permits) {
			sb.append(permit.getName() + ",");
		}
		return sb.toString().substring(0, sb.length() - 1);
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Permit> getPermits() {
		return permits;
	}

	public void setPermits(Set<Permit> permits) {
		this.permits = permits;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}