
package cn.zzrfdsn.webService.customerService;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.customerService.zzrfdsn.cn/")
public interface ICustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "associationDecidedzone", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.AssociationDecidedzone")
    @ResponseWrapper(localName = "associationDecidedzoneResponse", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.AssociationDecidedzoneResponse")
    public Integer associationDecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @return
     *     returns java.util.List<cn.zzrfdsn.customerservice.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<cn.zzrfdsn.customerservice.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNoAssociationDecidedzone", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindNoAssociationDecidedzone")
    @ResponseWrapper(localName = "findNoAssociationDecidedzoneResponse", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindNoAssociationDecidedzoneResponse")
    public List<Customer> findNoAssociationDecidedzone();

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.zzrfdsn.customerservice.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.zzrfdsn.customerservice.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHasAssociationDecidedzone", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindHasAssociationDecidedzone")
    @ResponseWrapper(localName = "findHasAssociationDecidedzoneResponse", targetNamespace = "http://service.customerService.zzrfdsn.cn/", className = "cn.zzrfdsn.customerservice.service.FindHasAssociationDecidedzoneResponse")
    public List<Customer> findHasAssociationDecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
